"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const read = name => fs.readFileSync(path.join(root,name),"utf8");
const program = read("Program.cs"), service = read("SemanticClassificationService.cs");
for (const source of [program,service,read("compose.yaml"),read("deploy/compose.curiosity.yaml")])
  assert.doesNotMatch(source, /ClassifierClient|QwenDeepAnalysisContract|DeepAnalysis__|OLLAMA_|--llm-benchmark|gpus:/);
assert.match(service, /regexClassifier\.Classify/);
assert.match(service, /"deterministic-regex"/);
assert.match(service, /"json-regex-v1"/);
assert.doesNotMatch(program, /AddSingleton<SqliteSemanticRuleStore>|AddHostedService<RegexTelemetryFlushService>/);
assert.match(program, /ConceptRuleSnapshot.Load[\s\S]*?WebApplication.CreateBuilder/);
assert.match(read("JobCatalog.cs"), /CanPersist\(current, classification\)/);
assert.doesNotMatch(read("JobCatalog.cs"), /DeepAnalyzeWithQwenAsync|PersistDeepAnalysisStateAsync/);
assert.match(program, /AddSingleton<SemanticClassificationService>/);
assert.match(program, /ConceptDiagnosticRequest request/);
assert.match(read("JobModels.cs"), /QwenDeepAnalysis\? QwenDeepAnalysis/);
assert.match(read("JobModels.cs"), /LlmDeepAnalysisRequestState/);
assert.match(read("SqliteSemanticRuleStore.cs"), /CREATE TABLE IF NOT EXISTS LlmEvaluationRunDetails/);
assert.match(read("JobSearchManager.csproj"), /Compile Remove="ClassifierClient\.cs;LlmHoldoutEvaluation\.cs;LlmHardwareBenchmark\.cs;LlmTechnicalPreflight\.cs;research\/\*\*\/\*\.cs"/);
const taxonomy=JSON.parse(read("JobConceptCatalog.json"));
assert.equal(taxonomy.concepts.length,85);
assert.equal(new Set(taxonomy.concepts.map(c=>c.id)).size,85);
assert.match(read("scripts/deploy-curiosity.sh"), /ancestor=jsm:\$old_sha/);
console.log("Model-free deterministic composition and persisted Qwen compatibility: PASS");
